### ISSUE TITLE
Install CDH

### ISSUE THREAD

**Issue by thommaa** [thommaa/SEBC#10]
Install the CDH 5.10 release

**Comment by thommaa** [comment]
Installation and configuration of cluster just completing at end of challenge: 

Cluster Setup
First Run Command

**Comment by thommaa** [comment]
My overall progress in the CDH installation was just too slow. 

was sightly struggling with java version JDK 1.8u111 
somehow the servers were unfortunately additionally slow.

**Comment by rsiwicki** [comment]
Generally seems that it is ok. There are a few command outputs missing.

**Comment by mfernest** [comment]
This is the second case so far I have heard of the local network impeding progress. I am sorry for such a frustrating experience.
